# build version format
version: 3.1.2.beta5.{build}

#enable rdp support
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#cache
cache:
- C:\tools\vcpkg\installed\
- C:\Dev\Libs\wxWidgets-3.1.1

# Free accounts have a max of 1, but ask anyway.
max_jobs: 4

environment:
  WXWIN: C:\Dev\Libs\wxWidgets-3.1.1
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
- cmd: >-
    cd C:\Tools\vcpkg\scripts\buildsystems\msbuild

    echo Installing curl

    vcpkg install curl:x86-windows-static

    curl -o vcpkg.targets https://raw.githubusercontent.com/RDCH106/vcpkg/6c90fa6791ea95dca33832430695f1878c62f851/scripts/buildsystems/msbuild/vcpkg.targets

    echo Installing freeimage

    vcpkg install freeimage:x86-windows-static

    echo Installing SFML

    vcpkg install sfml:x86-windows-static

    echo Finishing up vcpkg

    vcpkg integrate install

    IF NOT EXIST "%WXWIN%" appveyor DownloadFile "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1.7z"

    IF NOT EXIST "%WXWIN%" 7z x wxWidgets-3.1.1.7z -o%WXWIN% -aoa -y

    echo Hack to automatically detect libs

    xcopy C:\Tools\vcpkg\installed\x86-windows-static\lib "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC" /O /X /E /H /K /Q /Y

before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    SET PATH=%APPVEYOR_BUILD_FOLDER%;%WXWIN%;%PATH%

    msbuild %WXWIN%\build\msw\wx_vc14.sln /p:Configuration="Release" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m

platform:
  - Win32

configuration:
- Release
- Release - WinXP

build:
  project: build\msvc\SLADE.sln
  verbosity: normal
  parallel: true

before_package:
- cmd: >-
    git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/gitshort.txt

    set /P GITSHORT=<%TMP%/gitshort.txt

    set BUILD_ARCHIVE="%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%".7z
after_build:
- cmd: >-
    7z a %BUILD_ARCHIVE% dist -xr!.gitignore

    appveyor PushArtifact %BUILD_ARCHIVE%