# build version format
version: 3.1.2.{build}

#cache
cache:
- C:\Dev\Libs\wxWidgets
- C:\Dev\Libs\CURL
- C:\Dev\Libs\SFML-2.5.1
- C:\Dev\Libs\FreeImage

image: Visual Studio 2017

environment:
  WXWIN: C:\Dev\Libs\wxWidgets
  CURL: C:\Dev\Libs\CURL\third-party\libcurl
  CURLSRC: C:\Dev\Libs\CURL\
  SFML: C:\Dev\Libs\SFML-2.5.1
  FREEIMAGE: C:\Dev\Libs\FreeImage
  SFMLZIP: SFML-2.5.1-windows-vc14-32-bit.zip
  FREEIMAGEZIP: FreeImage3180Win32Win64.zip
  LIB: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib\

install:
- cmd: >-
    curl --version

    echo Installing or building the required dependencies.

    IF NOT EXIST "%SFML%" curl -fsS -L -v --create-dirs -o "%SFMLZIP%" "https://www.sfml-dev.org/files/%SFMLZIP%" && 7z x %SFMLZIP% -oC:\Dev\Libs -aoa -y

    IF NOT EXIST "%FREEIMAGE%" curl -fsS -L -v --create-dirs -o "%FREEIMAGEZIP%" "http://downloads.sourceforge.net/freeimage/%FREEIMAGEZIP%" && 7z x %FREEIMAGEZIP% -oC:\Dev\Libs -aoa -y

    IF NOT EXIST "%CURL%" git clone https://github.com/SteelTitanium/build-libcurl-windows.git %CURLSRC% && cd %CURLSRC% && call build.bat

    cd %APPVEYOR_BUILD_FOLDER%

    IF NOT EXIST "%WXWIN%" curl -fsS  -L -v --create-dirs -o "%WXWIN%" "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1-headers.7z" && curl -fsS  -L -v --create-dirs -o "%WXWIN%" "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxMSW-3.1.1_vc140_Dev.7z" && 7z x wxWidgets-3.1.1-headers.7z -o%WXWIN% -aoa -y && 7z x wxMSW-3.1.1_vc140_Dev.7z -o%WXWIN% -aoa -y

before_build:
- cmd: >-
    msbuild %WXWIN%\build\msw\wx_vc12.sln /p:Configuration="Release" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m

platform:
  - Win32

configuration:
- Release
- Release - WinXP

build:
  project: build\msvc\SLADE.sln
  verbosity: normal
  parallel: true

before_package:
- cmd: >-
    git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/gitshort.txt

    set /P GITSHORT=<%TMP%/gitshort.txt

    set BUILD_ARCHIVE="%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%".7z
after_build:
- cmd: >-
    7z a %BUILD_ARCHIVE% dist -xr!.gitignore

    appveyor PushArtifact %BUILD_ARCHIVE%

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))