# build version format
version: 3.1.2.{build}

#cache
cache:
- C:\Dev\Libs\wxWidgets-3.1.1
- C:\Dev\Libs\CURL
- C:\Dev\Libs\SFML-2.5.1
- C:\Dev\Libs\FreeImage

# Free accounts have a max of 1, but ask anyway.
max_jobs: 4

environment:
  WXWIN: C:\Dev\Libs\wxWidgets-3.1.1
  CURL: C:\Dev\Libs\CURL
  SFML: C:\Dev\Libs\SFML-2.5.1
  FREEIMAGE: C:\Dev\Libs\FreeImage
  SFMLZIP: SFML-2.5.1-windows-vc14-32-bit.zip
  FREEIMAGEZIP: FreeImage3180Win32Win64.zip
  WXWIN7Z: wxWidgets-3.1.1.7z

install:
- cmd: >-
   set PATH=%PATH%;%WXWIN%;%SFML%;%CURL%;%FREEIMAGE%

   echo "%SFML%"

    curl --version

    echo Installing or building the required dependencies.

    IF NOT EXIST "%SFML%" curl -fsS -L -v --create-dirs -o "%SFMLZIP%" "https://www.sfml-dev.org/files/%SFMLZIP%" && 7z x %SFMLZIP% -o%SFML% -aoa -y

    IF NOT EXIST "%FREEIMAGE%" curl -fsS -L -v --create-dirs -o "%FREEIMAGEZIP%" "http://downloads.sourceforge.net/freeimage/%FREEIMAGEZIP%" && 7z x %FREEIMAGEZIP% -o%FREEIMAGE% -aoa -y

    IF NOT EXIST "%CURL%" git clone https://github.com/SteelTitanium/build-libcurl-windows.git %CURL% && cd %CURL% && call build.bat

    IF NOT EXIST "%WXWIN%" curl -fsS  -L -v --create-dirs -o "%WXWIN7Z%" "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/%WXWIN7Z%" && 7z x %WXWIN7Z% -o%WXWIN% -aoa -y

    echo Cleaning up

    IF EXIST "%WXWIN%" del "%WXWIN7Z%"

    IF EXIST "%SFML%" del "%SFMLZIP%"

    IF EXIST "%FREEIMAGE%" del "%FREEIMAGEZIP%"

before_build:
- cmd: >-
    msbuild %WXWIN%\build\msw\wx_vc14.sln /p:Configuration="Release" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /m

platform:
  - Win32

configuration:
- Release
- Release - WinXP

build:
  project: build\msvc\SLADE.sln
  verbosity: normal
  parallel: true

before_package:
- cmd: >-
    git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/gitshort.txt

    set /P GITSHORT=<%TMP%/gitshort.txt

    set BUILD_ARCHIVE="%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%".7z
after_build:
- cmd: >-
    7z a %BUILD_ARCHIVE% dist -xr!.gitignore

    appveyor PushArtifact %BUILD_ARCHIVE%

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))