version: 3.1.2.{build}
configuration:
- Release
- Release - WinXP
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache: c:\tools\vcpkg\installed\
install:
- cmd: >-
    cd C:\Tools\vcpkg\scripts\buildsystems\msbuild

    vcpkg install sfml

    vcpkg install freeimage

    vcpkg install wxwidgets

    vcpkg install curl
before_build:
- cmd: >-
    cd C:\Tools\vcpkg\scripts\buildsystems\msbuild

    curl -o vcpkg.targets https://raw.githubusercontent.com/RDCH106/vcpkg/6c90fa6791ea95dca33832430695f1878c62f851/scripts/buildsystems/msbuild/vcpkg.targets

    vcpkg integrate install
build:
  project: build\msvc\SLADE.sln
  verbosity: normal
  parallel: true
before_package:
- cmd: >-
    git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/gitshort.txt

    set /P GITSHORT=<%TMP%/gitshort.txt

    set BUILD_ARCHIVE="%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%".7z
after_build:
- cmd: >-
    7z a %BUILD_ARCHIVE% dist -xr!.gitignore

    appveyor PushArtifact %BUILD_ARCHIVE%